{% set version = "3.01" %}

package:
  name: nsis
  version: {{ version }}

source:
  fn: nsis-{{ version }}.zip
  url: http://sourceforge.net/projects/nsis/files/NSIS%20{{ version.split(".")[0] }}/{{ version }}/nsis-{{ version }}.zip
  sha256: daa17556c8690a34fb13af25c87ced89c79a36a935bf6126253a9d9a5226367c

build:
  number: 1003
  skip: true  # [not (win and py27)]

requirements:
  build:
    - python
    - 7za

about:
  home: http://sourceforge.net/projects/nsis
  summary: Nullsoft Scriptable Install System
  license: CPL-1.0, zlib, bzip2, LGPL, BSD, UNKNOWN
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jakirkham
    - mbargull
    - msarahan
    - patricksnape
