{% set version = "3.01" %}

package:
  name: nsis
  version: {{ version }}

source:
  fn: nsis-{{ version }}.tar.bz2
  url: http://sourceforge.net/projects/nsis/files/NSIS%20{{ version.split(".")[0] }}/{{ version }}/nsis-{{ version }}-src.tar.bz2
  sha256: 604c011593be484e65b2141c50a018f1b28ab28c994268e4ecd377773f3ffba1

build:
  number: 0
  skip: true  # [not (win and py27)]
  script:
    - set
    - set "MSSDK=%WindowsSdkDir%"
    - scons ZLIB_W32="%LIBRARY_PREFIX%"     # [win32]
    - scons ZLIB_W64="%LIBRARY_PREFIX%"     # [win64]
    - scons PREFIX="%PREFIX%" install

requirements:
  build:
    - python
    - scons
    - zlib 1.2.*

  run:
    - vs2008_runtime
    - zlib 1.2.*

about:
  home: http://sourceforge.net/projects/nsis
  summary: Nullsoft Scriptable Install System
  license: CPL-1.0, zlib, bzip2
  license_file: COPYING

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - patricksnape
